txt = input("입력 텍스트:")
words = txt.split(" ")
print("사용된 단어의 개수=", len(words))
print(words)
print("입력 문자열 :", txt)
print("a 문자개수 :", txt.count("a"))
print("a 문자의 index 위치 :", txt.find("a"))
print("대문자 :", txt.upper())
print("소문자 :", txt.lower())
print("첫글자 대문자:", txt.title())
print("a 문자 Z로 변경:", txt.replace("a", "Z"))
